baseURL = "https://saga.udalf.world/"
languageCode = "en-us"
title = "Udalf Saga"
copyright = "Copyright Â© 2018"
theme = "indigo"

[params]
  Author = "Udalf"
  Description = "Udalf Saga"
  ShowBio = false
  PermalinkText = "ğŸ¿"